# Global settings
[global]
experiment_name = "learning_the_null"
meta_seeds = [1, 2, 3, 4, 5]  # Control initial data split to prevent data leakage
train_split = 0.7  # Data proportion for training
selection_folds = 10  # Number of cross-validation folds for model selection

# Experiment list
[experiments]
datasets = [
    "hepatitis",
    "wbc",
    "ionosphere",
    "breast",
    "cardio",
    "musk",
    "mammography",
    "shuttle"
]
models = [
    "iforest",
    "loda",
    "inne",
    "hbos",
    "mcd",  # Note: MCD+MUSK combination will be skipped
    "copod",
    "ecod"
]
